import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { Header } from '@/components/dashboard/Header';
import { ReportProvider } from '@/components/providers/ReportContext';
import { getAvailableMonths, getDefaultMonthData } from '@/lib/data';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'FNF 경영실적 대시보드',
  description: 'F&F 월별 재무제표 대시보드',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const index = await getAvailableMonths();
  const initialData = await getDefaultMonthData();

  return (
    <html lang="ko">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-slate-50`}>
        <ReportProvider
          initialData={initialData}
          availableMonths={index.availableMonths}
          defaultMonth={index.defaultMonth}
        >
          <Header />
          <main className="min-h-screen">
            {children}
          </main>
          <footer className="bg-slate-800 text-slate-400 py-4 text-center text-sm">
            FNF Financial Dashboard - Generated by Claude
          </footer>
        </ReportProvider>
      </body>
    </html>
  );
}
